services:
  ffc-pay-event-migrator:
    build:
      context: .
      target: development
    ports:
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
      - ./output:/home/node/output

  ffc-pay-event-store-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10180:10000"
      - "10181:10001"
      - "10182:10002"

volumes:
  azurite_data:

