{{- include "ffc-helm-library.container-config-map" (list . "ffc-pay-event-migrator.config-map") -}}
{{- define "ffc-pay-event-migrator.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
{{- end -}}
