environment: production
environmentCode:
name: ffc-pay-event-migrator
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-event-migrator

labels:
  component: service

containerConfigMap:
  name: ffc-pay-event-migrator-config-map

container:
  requestMemory: 150Mi
  requestCpu: 120m
  limitMemory: 500Mi
  limitCpu: 500m
  azureStorageConnectionString: dummy

cronJob:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  restartPolicy: Never
  successfulJobsHistoryLimit: 1
